I am able to get a conda environment setup and running from within Google Colab. However, this environment seems to be transient in nature. It does not show up in any new notebook I create, and I am not able to run the notebook normally. I have to run all my python code in one cell... But at least I know using conda to create my own environment in Google Colab is possible.

Check to see if conda is already installed

In [ ]:
!which conda

Nope, not installed. Go ahead and install it

I found a package **cartopy** that is not installed in my normal Google Colab environment. I want to use it so I will include it in my conda env create command below.

In [ ]:
import cartopy

ModuleNotFoundError: ignored

In [ ]:
# try to run the bare minimum to get a new conda env working
conda_path = ''
try:
    conda_path = !which conda
finally:
    print('')

if (len(conda_path) == 0):
    print('installing miniconda')
    !wget https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh && bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
    !conda update conda -y -q
    !source /usr/local/etc/profile.d/conda.sh
    !conda init 
    !conda install -n root _license -y -q
else:
    print('found miniconda')

conda_envs = !conda env list
res = [i for i in conda_envs if 'test36' in i]
if (len(res) == 0):
    print('not found test36 env', len(res))
    !conda create -y -q --name test36 python=3.6 libarchive cartopy
else:
    print('found test36 env', len(res))


installing miniconda
--2020-06-28 10:59:43--  https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.200.79, 104.18.201.79, 2606:4700::6812:c84f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.200.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh [following]
--2020-06-28 10:59:43--  https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58468498 (56M) [application/x-sh]
Saving to: ‘Miniconda3-4.5.4-Linux-x86_64.sh’

Miniconda3-4.5.4-Li 100%[===================>]  55.76M   172MB/s    in 0.3s    

2020-06-28 10:59:43 (172 MB/s) - ‘Minic

<pre>
You should see a lot of install activity above, similar to this:

installing miniconda
--2020-06-27 22:45:59--  https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c94f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh [following]
--2020-06-27 22:45:59--  https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58468498 (56M) [application/x-sh]
Saving to: ‘Miniconda3-4.5.4-Linux-x86_64.sh.1’

Miniconda3-4.5.4-Li 100%[===================>]  55.76M   180MB/s    in 0.3s    

2020-06-27 22:45:59 (180 MB/s) - ‘Miniconda3-4.5.4-Linux-x86_64.sh.1’ saved [58468498/58468498]

PREFIX=/usr/local
installing: python-3.6.5-hc3d631a_2 ...
Python 3.6.5 :: Anaconda, Inc.
installing: ca-certificates-2018.03.07-0 ...
...
unlinking: zlib-1.2.11-h7b6447c_3
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /usr/local
Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local

  added / updated specs: 
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.1.1g             |       h7b6447c_0         3.8 MB
...
    conda-package-handling-1.6.1|   py36h7b6447c_0         886 KB
    ------------------------------------------------------------
                                           Total:        48.8 MB

The following NEW packages will be INSTALLED:

    conda-package-handling: 1.6.1-py36h7b6447c_0
    tqdm:                   4.46.1-py_0         

The following packages will be UPDATED:

    ca-certificates:        2018.03.07-0         --> 2020.1.1-0          
... 
    tk:                     8.6.7-hc745277_3     --> 8.6.10-hbc83047_0   

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
no change     /usr/local/condabin/conda
...
no change     /usr/local/etc/profile.d/conda.csh
modified      /root/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - _license

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


not found test36 env 0
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local/envs/test36

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
...
    zlib-1.2.11                |       h7b6447c_3         103 KB
    ------------------------------------------------------------
                                           Total:        49.4 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
...
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

check if conda exists again, now you should see something like "/usr/loca/bin/conda"

In [ ]:
!which conda

/usr/local/bin/conda


Check on your environment

In [ ]:
!env

CUDNN_VERSION=7.6.5.32
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
CLOUDSDK_PYTHON=python3
_=/usr/bin/env
LANG=en_US.UTF-8
HOSTNAME=1a6abc06fc9c
OLDPWD=/
CLOUDSDK_CONFIG=/content/.config
NVIDIA_VISIBLE_DEVICES=all
DATALAB_SETTINGS_OVERRIDES={"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=\"172.28.0.2\""]}
ENV=/root/.bashrc
PAGER=cat
NCCL_VERSION=2.4.8
TF_FORCE_GPU_ALLOW_GROWTH=true
JPY_PARENT_PID=18
NO_GCE_CHECK=True
PWD=/content
HOME=/root
LAST_FORCED_REBUILD=20200609
CLICOLOR=1
DEBIAN_FRONTEND=noninteractive
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
GCE_METADATA_TIMEOUT=0
GLIBCPP_FORCE_NEW=1
TBE_CREDS_ADDR=172.28.0.1:8008
TERM=xterm-color
SHELL=/bin/bash
GCS_READ_CACHE_BLOCK_SIZE_MB=16
PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
MPLBACKEND=module://ipykernel.pylab.backend_inline
CUDA_PKG_VERSION=10-1=10.1.243-1
CUDA_VERSION=10.1.243
NVIDIA_DRIVER_CAPABILITIES=compute,utility
SHLVL=2
PYTHONPATH=/env/python
NVIDIA_RE

If everything looks like I am showing, with no errors, you can run python code in your new conda environment. However, this will only persist for one cell. Then next cell will revert back to your base Google Colab environment. This is because you are using %%bash, this command will open a shell and run the commands within the same cell, but will close down when you exit the cell. You can test if the correct environment is active using conda env list and conda list. I can see my new environment is active (*) and the new package cartopy is available now.

In [ ]:
%%bash
source activate test36
conda env list
conda list
python
import sys
import cartopy
#import libarchive
# maybe only need this the first time we run this notebook
sys.path.append('/usr/local/lib/python3.6/site-packages')

print("Python version")
print(sys.version)

# conda environments:
#
base                     /usr/local
test36                *  /usr/local/envs/test36

# packages in environment at /usr/local/envs/test36:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py36h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.1.1                      0  
cartopy                   0.17.0           py36h3e2e9bd_1  
certifi                   2020.6.20                py36_0  
cffi                      1.14.0           py36he30daa8_1  
chardet                   3.0.4                 py36_1003  
cryptography              2.9.2            py36h1ba5d50_0  
cycler                    0.10.0                   py36_0  
dbus                      1.13.16              hb2f20db_0  
expat                     2.2.9                

The next cell will revert back to the default shell that was opened when you started Google Colab

In [ ]:
import sys
print(sys.version)

3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]


Not sure how to get around this, and run multiple cells from within your own environment only invoking python once...

Also note that conda activate does not work. Only source activate works like this so far. Still looking at this option, but the hints in this error do not help.

In [ ]:
%%bash
conda activate test36

python
import sys
# maybe only need this the first time we run this notebook
sys.path.append('/usr/local/lib/python3.6/site-packages')

print("Python version")
print(sys.version)

# conda environments:
#
base                  *  /usr/local
test36                   /usr/local/envs/test36

Python version
3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0]



CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.




Additional info about the conda you just installed

In [ ]:
!conda info


     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.6.8.final.0
       virtual packages : __glibc=2.27
       base environment : /usr/local  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.18.4 CPython/3.6.8 Linux/4.19.104+ ubuntu/18.04.3 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False



Location of your environment inside this container

In [ ]:
!ls -rlt  /usr/local/envs

total 4
drwxr-xr-x 10 root root 4096 Jun 27 22:47 test36
